### PR TITLE
Signature calculation fix, AuthnRequest generation for POST binding and Extracting multiple values from Assertion attributes

### PR DESCRIPTION
**Pull request by pradeephkcisco**
Signature calculation fix, AuthnRequest generation for POST binding and Extracting multiple values from Assertion attributes.

1. Fixed issue with signature calculation for the Request sent using Redirect binding when RelayState is not empty.
2. Added function to get all the values for that attribute.
3. Added functions to build AuthnRequest body for POST binding.
4. Made changes to avoid empty DigestMethod tag when generating metadata.

### CODE REVIEW

**Comment by mraerino** [comment]
@russellhaering Any chances on merging this soon?
I really need the fix for the invalid metadata generation (https://github.com/russellhaering/gosaml2/pull/39/commits/534d4ae229986bb5dac37f7e15e63f1bc907aa29)

@pradeephkcisco maybe it would make sense to put this into an extra PR so it can be reviewed faster?

**Comment by sergey-rud** [comment]
Hello guys. As I understand, without this PR merged I cannot implement SAML SLO (Single Logout) using this (russellhaering/gosaml2) package?

**Comment by pradeephkcisco** [comment]
@russellhaering would it be possible to review and merge these changes.

**Comment by russellhaering** [comment]
@pradeephkcisco thank you for authoring and maintaining this branch, and to the rest of you for your patience. I haven't given this the attention it deserved.

I just merged the branch and performed some minor rebasing and cleanup. I'm undertaking a little more maintenance, and plan to tag a release in the next few hours.

**Pull request merged**
