### PR TITLE
Use AES cipher for MethodRSAv1_5

### PR DESCRIPTION
**Pull request by unknwon**
AES is considered to be stronger than DES.

In addition:

1. Gofmt the file
2. Fix potential panic when there is no "signing" or "encryption" `KeyDescriptor`

### CODE REVIEW

**Comment by nicksnyder** [comment]
@unknwon What is the difference between this PR and https://github.com/russellhaering/gosaml2/pull/58?

@russellhaering Thanks for your work on this library; we use it at Sourcegraph! We would be happy to sponsor the work to get this PR merged so we don't need to maintain a fork.

**Comment by unknwon** [comment]
@nicksnyder There is no difference in terms of changes, but I can't edit @beyang's PR (title, description).

**Comment by ElizabethStirling** [comment]
@russellhaering wanted to follow up on this after the holidays. Again, Sourcegraph would be happy to sponsor this work in order to avoid maintaining a fork.

**Comment by mfridman** [comment]
+1 for this. Anything outside contributors can do to push this through ?

**Comment by beyang** [comment]
Thank you!

**Pull request merged**
